services:
  postgres:
    image: "postgres:latest"
    container_name: lms_postgres
    environment:
      - "POSTGRES_DB=lms_db"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  keycloak:
      image: quay.io/keycloak/keycloak:26.0.0
      command:
        - start-dev
        - --http-relative-path=/auth
      environment:
         KC_BOOTSTRAP_ADMIN_USERNAME: admin
         KC_BOOTSTRAP_ADMIN_PASSWORD: admin
         KC_DB: postgres
         KC_DB_URL: jdbc:postgresql://keycloak-db:5432/postgres
         KC_DB_USERNAME: postgres
         KC_DB_PASSWORD: postgres
      ports:
        - "8081:8080"
      depends_on:
        - keycloak-db
  keycloak-db:
    image: "postgres:latest"
    container_name: keycloak_db_container
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    labels:
      - "org.springframework.boot.service-connection=false"
    ports:
      - "2345:5432"
  api:
    build: .
    container_name: lms_api
    ports:
      - "8011:8011"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lms_db?currentSchema=public
      - SPRING_LIQUIBASE_DEFAULT_SCHEMA=public
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    labels:
      - "org.springframework.boot.ignore=true"
  minio:
    image: minio/minio
    container_name: lms_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/lms-bucket;
      /usr/bin/mc anonymous set public myminio/lms-bucket;
      exit 0;
      "
volumes:
  postgres_data:
  minio_data: